# Generated by Django 5.1.5 on 2025-01-30 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reservation_date_reservation_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
